[project]
name = "day-15"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.121.3",
    "uvicorn>=0.38.0",
]

[tool.uv.workspace]
members = [
    "ust_employee_telecom",
]
